//go:build go1.22

// Package virest provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package virest

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for InfoStatus.
const (
	Completed InfoStatus = "completed"
	Failed    InfoStatus = "failed"
	Pending   InfoStatus = "pending"
	Running   InfoStatus = "running"
)

// Error defines model for Error.
type Error struct {
	// Code Error code
	Code string `json:"code"`

	// Message Human-readable error message
	Message string `json:"message"`
}

// InfoJob defines model for InfoJob.
type InfoJob struct {
	// CreatedAt Timestamp when the job was created
	CreatedAt time.Time `json:"createdAt"`

	// Error Error message if the info extraction failed
	Error  *string    `json:"error,omitempty"`
	Result *VideoInfo `json:"result,omitempty"`

	// Status Current status of the info extraction job
	Status InfoStatus `json:"status"`

	// UpdatedAt Timestamp when the job was last updated
	UpdatedAt time.Time `json:"updatedAt"`

	// Uuid Unique identifier for the info job
	Uuid openapi_types.UUID `json:"uuid"`

	// VideoPath Path to the video file being inspected
	VideoPath string `json:"videoPath"`
}

// InfoRequest defines model for InfoRequest.
type InfoRequest struct {
	// Uuid Client-provided UUID for the info job
	Uuid openapi_types.UUID `json:"uuid"`

	// VideoPath Path to the video file to inspect
	VideoPath string `json:"videoPath"`
}

// InfoStatus Current status of the info extraction job
type InfoStatus string

// VideoInfo defines model for VideoInfo.
type VideoInfo struct {
	// ChapterDurationsSeconds Duration of each chapter in seconds
	ChapterDurationsSeconds []float64 `json:"chapterDurationsSeconds"`

	// TotalDurationSeconds Total duration of the video in seconds
	TotalDurationSeconds float64 `json:"totalDurationSeconds"`
}

// CreateInfoJSONRequestBody defines body for CreateInfo for application/json ContentType.
type CreateInfoJSONRequestBody = InfoRequest

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// CreateInfoWithBody request with any body
	CreateInfoWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateInfo(ctx context.Context, body CreateInfoJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetInfoStatus request
	GetInfoStatus(ctx context.Context, uuid openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) CreateInfoWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateInfoRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateInfo(ctx context.Context, body CreateInfoJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateInfoRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetInfoStatus(ctx context.Context, uuid openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetInfoStatusRequest(c.Server, uuid)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewCreateInfoRequest calls the generic CreateInfo builder with application/json body
func NewCreateInfoRequest(server string, body CreateInfoJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateInfoRequestWithBody(server, "application/json", bodyReader)
}

// NewCreateInfoRequestWithBody generates requests for CreateInfo with any type of body
func NewCreateInfoRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/info")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetInfoStatusRequest generates requests for GetInfoStatus
func NewGetInfoStatusRequest(server string, uuid openapi_types.UUID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "uuid", runtime.ParamLocationPath, uuid)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/info/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// CreateInfoWithBodyWithResponse request with any body
	CreateInfoWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateInfoResponse, error)

	CreateInfoWithResponse(ctx context.Context, body CreateInfoJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateInfoResponse, error)

	// GetInfoStatusWithResponse request
	GetInfoStatusWithResponse(ctx context.Context, uuid openapi_types.UUID, reqEditors ...RequestEditorFn) (*GetInfoStatusResponse, error)
}

type CreateInfoResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *InfoJob
	JSON400      *Error
	JSON409      *Error
	JSON500      *Error
}

// Status returns HTTPResponse.Status
func (r CreateInfoResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateInfoResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetInfoStatusResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *InfoJob
	JSON404      *Error
	JSON500      *Error
}

// Status returns HTTPResponse.Status
func (r GetInfoStatusResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetInfoStatusResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// CreateInfoWithBodyWithResponse request with arbitrary body returning *CreateInfoResponse
func (c *ClientWithResponses) CreateInfoWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateInfoResponse, error) {
	rsp, err := c.CreateInfoWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateInfoResponse(rsp)
}

func (c *ClientWithResponses) CreateInfoWithResponse(ctx context.Context, body CreateInfoJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateInfoResponse, error) {
	rsp, err := c.CreateInfo(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateInfoResponse(rsp)
}

// GetInfoStatusWithResponse request returning *GetInfoStatusResponse
func (c *ClientWithResponses) GetInfoStatusWithResponse(ctx context.Context, uuid openapi_types.UUID, reqEditors ...RequestEditorFn) (*GetInfoStatusResponse, error) {
	rsp, err := c.GetInfoStatus(ctx, uuid, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetInfoStatusResponse(rsp)
}

// ParseCreateInfoResponse parses an HTTP response from a CreateInfoWithResponse call
func ParseCreateInfoResponse(rsp *http.Response) (*CreateInfoResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateInfoResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest InfoJob
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetInfoStatusResponse parses an HTTP response from a GetInfoStatusWithResponse call
func ParseGetInfoStatusResponse(rsp *http.Response) (*GetInfoStatusResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetInfoStatusResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest InfoJob
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Start a new video info extraction job
	// (POST /info)
	CreateInfo(w http.ResponseWriter, r *http.Request)
	// Get video info job status
	// (GET /info/{uuid})
	GetInfoStatus(w http.ResponseWriter, r *http.Request, uuid openapi_types.UUID)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// CreateInfo operation middleware
func (siw *ServerInterfaceWrapper) CreateInfo(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateInfo(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetInfoStatus operation middleware
func (siw *ServerInterfaceWrapper) GetInfoStatus(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "uuid" -------------
	var uuid openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "uuid", r.PathValue("uuid"), &uuid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "uuid", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetInfoStatus(w, r, uuid)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("POST "+options.BaseURL+"/info", wrapper.CreateInfo)
	m.HandleFunc("GET "+options.BaseURL+"/info/{uuid}", wrapper.GetInfoStatus)

	return m
}

type CreateInfoRequestObject struct {
	Body *CreateInfoJSONRequestBody
}

type CreateInfoResponseObject interface {
	VisitCreateInfoResponse(w http.ResponseWriter) error
}

type CreateInfo201JSONResponse InfoJob

func (response CreateInfo201JSONResponse) VisitCreateInfoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateInfo400JSONResponse Error

func (response CreateInfo400JSONResponse) VisitCreateInfoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateInfo409JSONResponse Error

func (response CreateInfo409JSONResponse) VisitCreateInfoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type CreateInfo500JSONResponse Error

func (response CreateInfo500JSONResponse) VisitCreateInfoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetInfoStatusRequestObject struct {
	Uuid openapi_types.UUID `json:"uuid"`
}

type GetInfoStatusResponseObject interface {
	VisitGetInfoStatusResponse(w http.ResponseWriter) error
}

type GetInfoStatus200JSONResponse InfoJob

func (response GetInfoStatus200JSONResponse) VisitGetInfoStatusResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetInfoStatus404JSONResponse Error

func (response GetInfoStatus404JSONResponse) VisitGetInfoStatusResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetInfoStatus500JSONResponse Error

func (response GetInfoStatus500JSONResponse) VisitGetInfoStatusResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Start a new video info extraction job
	// (POST /info)
	CreateInfo(ctx context.Context, request CreateInfoRequestObject) (CreateInfoResponseObject, error)
	// Get video info job status
	// (GET /info/{uuid})
	GetInfoStatus(ctx context.Context, request GetInfoStatusRequestObject) (GetInfoStatusResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// CreateInfo operation middleware
func (sh *strictHandler) CreateInfo(w http.ResponseWriter, r *http.Request) {
	var request CreateInfoRequestObject

	var body CreateInfoJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateInfo(ctx, request.(CreateInfoRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateInfo")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateInfoResponseObject); ok {
		if err := validResponse.VisitCreateInfoResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetInfoStatus operation middleware
func (sh *strictHandler) GetInfoStatus(w http.ResponseWriter, r *http.Request, uuid openapi_types.UUID) {
	var request GetInfoStatusRequestObject

	request.Uuid = uuid

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetInfoStatus(ctx, request.(GetInfoStatusRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetInfoStatus")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetInfoStatusResponseObject); ok {
		if err := validResponse.VisitGetInfoStatusResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xWXW/bNhT9KwS3RzlWOjlN9ZY1QeehGLJ89CUIBlq8ipiJHyEvnRiB//tASrLlSJmD",
	"oQ320irS5T3Hh+d+PNNCS6MVKHQ0f6auqECy+HhmrbbhwVhtwKKA+LrQHML/HFxhhUGhFc2bYBK/JRSe",
	"mDQ10JzO//h28nV++tfF2Z/XZ5dXNKG4MuGDQyvUHV0nVIJz7G4k5W9eMjWxwDhb1EAgInTRfZCrCshS",
	"cNDEMKyIcESoJasFH8KtE2rhwQsLnOY3tOXbJb3dxOvFPRQY6M1VqX/XixEdLDAEfoJD5ldCgkMmDXms",
	"QBGsgNzrBXlkjrSnaEJLbSVDmlPOECYoJIypA90ljMnd8iaijBhClZrAE1pWhDBSMlEDH8tqwfk6Ev/Z",
	"Qklz+tN0a4Np64Hpt6Bp+P3hiEOG3u07EqIvm8h1Qr3h/0Gimjkk7dE36+S94EOUayUePBDBQaEoBVhS",
	"arvV6l4v+gAxx0ju6K1zhtUQILwlqGPKxoKlqIEsQKg7IpQzUCDs92GL3GrcR0x6PusL+ppVL+DBg8Oh",
	"XccF+lwLUDgxVgdITq6v56djGm2LbTZL4ThL0wl8+LSYZIc8m7CPh0eTLDs6ms2yLE3T9MeIirpTdIfQ",
	"NIa4qdRLAQfy7+Vb1d4yeE3My43nX6jmrQWFpLkvosfLr1VOeRlADSgeyCTUeqWap1BANbQ2b4r1dkSq",
	"bR0Om1DFDII99ZYFTHcJhVZ8hHIXEcgCKyrSniRCEdce6ql6c3icpsnuPwez24QKBBnTb8tS+0Xdq0nl",
	"5QJs4N2+YNayVfxbI6s7Iq8yvQpRhPf4bn0wTvbjh0Au2U/phQ9G+SSvajp0SUgo2nvZ/REn5/NYRp0d",
	"1B2RgIwzZKS0WvZ8HSBRYPRyvGkSrpqcnM+DR8G6JuPhQXqQBhW1AcWMoDn9Jb5KaJh6UchpR8ZoN9Jz",
	"P8dO4ggjCh43ig5MSx4FVoSR4rXeIDhIoxFUsaKRTyPUnG8wolkbscHhr5qvms1BIahIjBlTiyIem967",
	"wK5bPd4yYbomt969UbQemuFmtHJNgXxID78rdFgFIuyutPO2VXbznThfFOBc6es6ej9L0+/Go1nMRlnE",
	"tYfYTp+A++nH456ozaxozIOVcI1fWB0WuBWBJ+EwLgWz91ECwSpWEwd2CbZZHmMDcF5KZlc0p5fILO4r",
	"hngm1tX0OcyNdaB0ByPVdQHorXKxWxWDAcH+BeJlDX0B7E2fUN+WSUCwjuY3g3ZZQaN0fwo1WUX4bpot",
	"QjEJ22m8WzNJT+09c3t9O6iv9F3ry22WyyzN3sNHLa7SSErtFf9fWfgLYN9XfYFiYDw55pqvughDFpZQ",
	"ayOjVWNs2DFtTXNaIZp8Oq1DXKUd5sfpcUrXt+t/AgAA//+xaG7rMQ4AAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
